theme: jekyll-theme-cayman
title: Mita Studio
description: The Next Generation LLM Chat Platform with Unlimited Customization
show_downloads: false
google_analytics:
github:
  is_project_page: true
  repository_url: https://github.com/goodvirus/Mita-Studio